### import Libs(Toolkit)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
%matplotlib inline

### loading data and explore

In [91]:
df=pd.read_csv("Summer22_FootballTransfers.csv")
df.head()

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
0,Amine Gouiri,Centre-Forward,22.0,OGC Nice,Ligue 1,France,Stade Rennais FC,Ligue 1,France,€42.00m,9/1/2022
1,Umar Sadiq,Centre-Forward,25.0,UD Almería,LaLiga,Spain,Real Sociedad,LaLiga,Spain,€18.00m,9/1/2022
2,Carlos Soler,Central Midfield,25.0,Valencia CF,LaLiga,Spain,Paris Saint-Germain,Ligue 1,France,€50.00m,9/1/2022
3,Manuel Akanji,Centre-Back,27.0,Borussia Dortmund,Bundesliga,Germany,Manchester City,Premier League,England,€30.00m,9/1/2022
4,Wout Faes,Centre-Back,24.0,Stade Reims,Ligue 1,France,Leicester City,Premier League,England,€10.00m,9/1/2022

### Explore dataset

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33625 entries, 0 to 33624
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 33620 non-null  object
 1   position             33615 non-null  object
 2   age                  33477 non-null  float64
 3   origin_club          33620 non-null  object
 4   league_origin_club   32685 non-null  object
 5   country_origin_club  32690 non-null  object
 6   new_club             33615 non-null  object
 7   league_new_club      28047 non-null  object
 8   country_new_club     28051 non-null  object
 9   cost                 33621 non-null  object
 10  date_of_transfer     33625 non-null  object
dtypes: float64(1), object(10)
memory usage: 2.8+ MB

In [93]:
# check values null
df.isnull().sum()

name                      5
position                 10
age                     148
origin_club               5
league_origin_club      940
country_origin_club     935
new_club                 10
league_new_club        5578
country_new_club       5574
cost                      4
date_of_transfer          0
dtype: int64

In [94]:
df.columns

Index(['name', 'position', 'age', 'origin_club', 'league_origin_club',
       'country_origin_club', 'new_club', 'league_new_club',
       'country_new_club', 'cost', 'date_of_transfer'],
      dtype='object')

In [95]:
df.origin_club.value_counts()

Without Club                    853
Atalanta BC                      60
Unknown                          58
Genoa CFC                        43
US Sassuolo                      37
                               ...
KF Maliqi                         1
IF Karlstad Fotboll               1
Balmazújváros FC                  1
Joinville Esporte Clube (SC)      1
Esperance Tunis U21               1
Name: origin_club, Length: 5819, dtype: int64

In [96]:
df.new_club.value_counts()

Without Club           4950
Retired                 356
Unknown                 225
Career break             28
Potenza Calcio           26
                       ...
Gangneung Citizen         1
Jednota Banova            1
Al-Hamriyah               1
Little Rock Rangers       1
Slavia Sofia II           1
Name: new_club, Length: 6317, dtype: int64

check columns which name is not found (null)

In [97]:
df["name"].isnull().sum()

5

In [98]:
df[df["name"].isnull()]

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
2753,NaN,NaN,25.0,Without Club,NaN,NaN,University of Pretoria FC,South Africa,South Africa,€25Th.,8/23/2022
2754,NaN,NaN,30.0,Difaâ El Jadida,Botola Pro Inwi,Morocco,Olympique Khouribga,Botola Pro Inwi,Morocco,€325Th.,8/23/2022
2755,NaN,NaN,22.0,HNK Cibalia Vinkovci,Prva NL,Croatia,NK Lucko,Croatia,Croatia,€100Th.,8/23/2022
2756,NaN,NaN,25.0,Torino FC,Serie A,Italy,Palermo FC,Serie B,Italy,€1.60m,8/23/2022
2757,NaN,NaN,22.0,FC Porto,Liga Portugal,Portugal,Casa Pia AC,Liga Portugal,Portugal,€3.00m,8/23/2022

explore data which origin club == without club

In [99]:
df[df["origin_club"] == "Without Club"]

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
155,Milán Nemes,Left-Back,25.0,Without Club,NaN,NaN,Putnok FC,Hungary,Hungary,€75Th.,9/1/2022
193,Alec Mudimu,Centre-Back,27.0,Without Club,NaN,NaN,Caernarfon Town,Cymru Premier,Wales,€200Th.,9/1/2022
526,Stojan Vranjes,midfield,35.0,Without Club,NaN,NaN,FK Sloboda Tuzla,Premijer Liga,Bosnia-Herzegovina,€225Th.,9/1/2022
529,Oliver Kragl,Left Midfield,32.0,Without Club,NaN,NaN,SV Ried,Bundesliga,Austria,€500Th.,9/1/2022
534,Oguzhan Özyakup,Central Midfield,29.0,Without Club,NaN,NaN,Fortuna Sittard,Eredivisie,Netherlands,€1.00m,9/1/2022
...,...,...,...,...,...,...,...,...,...,...,...
33274,Pedro Chic,midfield,NaN,Without Club,NaN,NaN,Quiché FC,Guatemala,Guatemala,€10Th.,7/1/2022
33395,Fitrah Ramadhan,Defensive Midfield,23.0,Without Club,NaN,NaN,PSCS Cilacap,Liga 2,Indonesia,€10Th.,7/1/2022
33459,Anrie Chase,Centre-Back,18.0,Without Club,NaN,NaN,VfB Stuttgart II,Regionalliga Südwest,Germany,€300Th.,7/1/2022
33468,Nazih Ilihoum,Central Midfield,22.0,Without Club,NaN,NaN,ORB Akbou,Algeria,Algeria,€75Th.,7/1/2022
33498,Marco Contescu,Centre-Forward,19.0,Without Club,NaN,NaN,Unirea Sannicolau Mare,Romania,Romania,€10Th.,7/1/2022

In [11]:
df.league_origin_club.value_counts()

Italy                         930
Spain                         587
Premier League                496
Serie A                       489
Liga 2                        441
                             ...
Vierde Divisie A Saturday       1
Derde Divisie Sunday            1
Regional League East            1
Vierde Divisie B Sunday         1
U17-Bundesliga Süd/Südwest      1
Name: league_origin_club, Length: 462, dtype: int64

In [15]:
df[df["origin_club"] == "Without Club"].shape

(853, 11)

In [16]:
df[df["origin_club"] == "Without Club"]

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
155,Milán Nemes,Left-Back,25.0,Without Club,NaN,NaN,Putnok FC,Hungary,Hungary,€75Th.,9/1/2022
193,Alec Mudimu,Centre-Back,27.0,Without Club,NaN,NaN,Caernarfon Town,Cymru Premier,Wales,€200Th.,9/1/2022
526,Stojan Vranjes,midfield,35.0,Without Club,NaN,NaN,FK Sloboda Tuzla,Premijer Liga,Bosnia-Herzegovina,€225Th.,9/1/2022
529,Oliver Kragl,Left Midfield,32.0,Without Club,NaN,NaN,SV Ried,Bundesliga,Austria,€500Th.,9/1/2022
534,Oguzhan Özyakup,Central Midfield,29.0,Without Club,NaN,NaN,Fortuna Sittard,Eredivisie,Netherlands,€1.00m,9/1/2022
...,...,...,...,...,...,...,...,...,...,...,...
33274,Pedro Chic,midfield,NaN,Without Club,NaN,NaN,Quiché FC,Guatemala,Guatemala,€10Th.,7/1/2022
33395,Fitrah Ramadhan,Defensive Midfield,23.0,Without Club,NaN,NaN,PSCS Cilacap,Liga 2,Indonesia,€10Th.,7/1/2022
33459,Anrie Chase,Centre-Back,18.0,Without Club,NaN,NaN,VfB Stuttgart II,Regionalliga Südwest,Germany,€300Th.,7/1/2022
33468,Nazih Ilihoum,Central Midfield,22.0,Without Club,NaN,NaN,ORB Akbou,Algeria,Algeria,€75Th.,7/1/2022
33498,Marco Contescu,Centre-Forward,19.0,Without Club,NaN,NaN,Unirea Sannicolau Mare,Romania,Romania,€10Th.,7/1/2022

explore data which new club == without club

In [13]:
df[df["new_club"] == "Without Club"].shape

(4950, 11)

In [14]:
df[df["new_club"] == "Without Club"]

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
461,Anwar Mediero,Left Winger,20.0,Atalanta Bergamo Weitere,Italy,Italy,Without Club,NaN,NaN,€25Th.,9/1/2022
524,Chris Maguire,Right Winger,33.0,Lincoln City,League One,England,Without Club,NaN,NaN,€250Th.,9/1/2022
528,Danny Rose,Left-Back,32.0,Watford FC,Championship,England,Without Club,NaN,NaN,€2.20m,9/1/2022
531,Ryan Bennett,Centre-Back,32.0,Swansea City,Championship,Wales,Without Club,NaN,NaN,€1.00m,9/1/2022
533,Tarik Camdal,defence,31.0,Tuzlaspor,1.Lig,Turkey,Without Club,NaN,NaN,€100Th.,9/1/2022
...,...,...,...,...,...,...,...,...,...,...,...
33605,Hossein Norouzi,Goalkeeper,NaN,Fajr Sepasi Shiraz,Azadegan League,Iran,Without Club,NaN,NaN,€25Th.,7/1/2022
33606,Mohammadreza Nouri,Defensive Midfield,22.0,Khosheh Talaei Saveh,Azadegan League,Iran,Without Club,NaN,NaN,€25Th.,7/1/2022
33607,Erfan Sharifi,Left-Back,NaN,Khosheh Talaei Saveh,Azadegan League,Iran,Without Club,NaN,NaN,€25Th.,7/1/2022
33615,Dhruv Vikram Singh,midfield,19.0,FK Timok Zajecar,Serbia,Serbia,Without Club,NaN,NaN,€10Th.,7/1/2022
33620,Nursultan Nurlanuly,Central Midfield,20.0,Baikonur Kyzylorda,Pervaya Liga,Kazakhstan,Without Club,NaN,NaN,€10Th.,7/1/2022

when origin_club,new_club = without_club ==> league_origin_club,country_origin_club,league_new_club,country_new_club = NaN

then we are fill this value by Unknown

explore data with new_club == "UnKnown"

In [17]:
df[df["new_club"] == "Unknown"].shape

(225, 11)

In [18]:
df[df["new_club"] == "Unknown"]

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
542,Gustavo Aprile,Left Midfield,34.0,Without Club,NaN,NaN,Unknown,NaN,NaN,€25Th.,9/1/2022
1000,Simone Pippi,Second Striker,23.0,SSD Sampierana,Italy,Italy,Unknown,NaN,NaN,€25Th.,8/31/2022
1748,Ahad Azam,Defensive Midfield,30.0,Bnei Eilat,Israel,Israel,Unknown,NaN,NaN,€100Th.,8/27/2022
1759,Vukasin Jovkovic,Centre-Forward,21.0,Olympiakos Nicosia,Protathlima Cyta,Cyprus,Unknown,NaN,NaN,€25Th.,8/27/2022
2718,Valeriy Blazhko,Centre-Forward,21.0,Metalist 1925 Kharkiv,Premier Liga,Ukraine,Unknown,NaN,NaN,€25Th.,8/23/2022
...,...,...,...,...,...,...,...,...,...,...,...
27633,Ignacio Rodríguez,defence,23.0,Tacuary Football Club,Primera División Clausura,Paraguay,Unknown,NaN,NaN,€25Th.,7/1/2022
27638,Víctor Yánez,defence,23.0,Tacuary Football Club,Primera División Clausura,Paraguay,Unknown,NaN,NaN,€25Th.,7/1/2022
27639,Germán Mansilla,midfield,24.0,Racing Club de Montevideo,Liga de Ascenso,Uruguay,Unknown,NaN,NaN,€25Th.,7/1/2022
32777,Duccio Falconi,midfield,20.0,Vivi Altotevere Sansepolcro,Italy,Italy,Unknown,NaN,NaN,€25Th.,7/1/2022
33570,Danilo Rojas,midfield,27.0,Sportivo Ameliano,Primera División Clausura,Paraguay,Unknown,NaN,NaN,€50Th.,7/1/2022

explore data with origin_club == "UnKnown"

In [19]:
df[df["origin_club"] == "Unknown"].shape

(58, 11)

In [20]:
df[df["origin_club"] == "Unknown"]

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
2739,Nicholas Osei Bonsu,Attacking Midfield,21.0,Unknown,NaN,NaN,Asante Kotoko SC,Premier League,Ghana,€25Th.,8/23/2022
2899,Houssem Gatfia,Attacking Midfield,23.0,Unknown,NaN,NaN,Avenir Sportif Rejiche,Ligue I Pro,Tunisia,€25Th.,8/22/2022
3862,Luiz Ferreira,attack,24.0,Unknown,NaN,NaN,Diyala FC,Iraq,Iraq,€25Th.,8/17/2022
4432,Hernán Salazar,Centre-Forward,32.0,Unknown,NaN,NaN,A.S.D. Pol. Bonorva,Italy,Italy,€25Th.,8/13/2022
5068,Jovan Radovic,Right-Back,21.0,Unknown,NaN,NaN,FK FAP Priboj,Serbia,Serbia,€50Th.,8/11/2022
5974,Anxhelo Kojdheli,Centre-Back,18.0,Unknown,NaN,NaN,AC Mezzocorona,Italy,Italy,€25Th.,8/8/2022
6883,Jakob Judez,Right-Back,23.0,Unknown,NaN,NaN,NK Trebnje,Slovenia,Slovenia,€50Th.,8/4/2022
7462,Gift Emmanuel Orban,Centre-Forward,20.0,Unknown,NaN,NaN,Stabæk Fotball,OBOS-ligaen,Norway,€100Th.,8/3/2022
8021,Ciprian Gliga,Right Midfield,25.0,Unknown,NaN,NaN,Marosvásárhelyi SE,Romania,Romania,€50Th.,8/1/2022
8229,Simeon Betapudi,Right Winger,18.0,Unknown,NaN,NaN,Belmont Bruins (Belmont University),United States,United States,€10Th.,8/1/2022
8442,Walid Fuseini,Central Midfield,22.0,Unknown,NaN,NaN,Nsoatreman FC,Premier League,Ghana,€25Th.,8/1/2022
9286,Amine Sebbar,Centre-Back,30.0,Unknown,NaN,NaN,AS Salé,Morocco,Morocco,€125Th.,7/29/2022
9459,Bence Iszlai,Defensive Midfield,32.0,Unknown,NaN,NaN,VLS Veszprém,Hungary,Hungary,€150Th.,7/28/2022
10156,John Alvbage,Goalkeeper,39.0,Unknown,NaN,NaN,Retired,NaN,NaN,€50Th.,7/27/2022
12416,Cephas Doku,Centre-Forward,24.0,Unknown,NaN,NaN,FK Dordoi Bishkek,BC Olimp Premier League,Kyrgyzstan,€25Th.,7/20/2022
12546,Eliot Cassas,Goalkeeper,29.0,Unknown,NaN,NaN,Club Deportivo FATIC,Bolivia,Bolivia,€25Th.,7/20/2022
12670,Reynaldo Polo,Goalkeeper,30.0,Unknown,NaN,NaN,SD Panamá Oeste,Panama,Panama,€50Th.,7/20/2022
14526,Boban Djordjevic,Centre-Forward,25.0,Unknown,NaN,NaN,OSK Igalo,Druga Liga,Montenegro,€100Th.,7/15/2022
14621,Abdullah Al-Samtai,Defensive Midfield,25.0,Unknown,NaN,NaN,Al-Khaleej,Professional League,Saudi Arabia,€25Th.,7/15/2022
16332,Balsa Goranovic,midfield,24.0,Unknown,NaN,NaN,OFK Niksic,Druga Liga,Montenegro,€100Th.,7/11/2022
16387,Juan Jiménez,Goalkeeper,24.0,Unknown,NaN,NaN,Los Cabos United,Mexico,Mexico,€200Th.,7/11/2022
16549,Armando Vargas,Right Winger,33.0,Unknown,NaN,NaN,Moca FC,Liga Dominicana - Liguilla,Dominican Republic,€200Th.,7/10/2022
17211,Gabriel Gomes,Centre-Back,22.0,Unknown,NaN,NaN,Grêmio Esportivo Brasil (RS),Série C,Brazil,€150Th.,7/8/2022
17396,Leandro Ávila,Right Winger,24.0,Unknown,NaN,NaN,Herrera FC,Liga Panameña Clausura,Panama,€75Th.,7/7/2022
17827,Jordan Blondel,Attacking Midfield,30.0,Unknown,NaN,NaN,US Alençon,N 3 - Normandie,France,€200Th.,7/6/2022
17961,Osman Ibañez,Right-Back,27.0,Unknown,NaN,NaN,Libertad Gran Mamoré FC,Bolivia,Bolivia,€100Th.,7/6/2022
18690,Jovica Dacevic,Right-Back,22.0,Unknown,NaN,NaN,FK Sutjeska Foca,Prva Liga RS,Bosnia-Herzegovina,€50Th.,7/4/2022
18775,Hesller Morales,midfield,27.0,Unknown,NaN,NaN,CD Real Sociedad de Tocoa,Liga Nacional Apertura,Honduras,€50Th.,7/4/2022
20937,Michel Rosenblum,Right-Back,33.0,Unknown,NaN,NaN,CSC Peciu Nou,Romania,Romania,€10Th.,7/1/2022
21422,Florin Nanu,Left Midfield,38.0,Unknown,NaN,NaN,CSO Deta,Romania,Romania,€10Th.,7/1/2022
21588,Madalin Stancu,Central Midfield,30.0,Unknown,NaN,NaN,CS Millenium Giarmata,Romania,Romania,€10Th.,7/1/2022
21795,Márk Tóth,Attacking Midfield,26.0,Unknown,NaN,NaN,Pécsi EAC,Hungary,Hungary,€10Th.,7/1/2022
22176,Zoltan Mihaly,Centre-Back,26.0,Unknown,NaN,NaN,Marosvásárhelyi SE,Romania,Romania,€10Th.,7/1/2022
22327,Bogdan Centea,Left Midfield,29.0,Unknown,NaN,NaN,ACS Carani,Romania,Romania,€10Th.,7/1/2022
22468,Borys Barone,Centre-Forward,28.0,Unknown,NaN,NaN,Cerro Largo FC,Primera División,Uruguay,€75Th.,7/1/2022
23321,Marco Giuricici,Central Midfield,26.0,Unknown,NaN,NaN,CSC Peciu Nou,Romania,Romania,€25Th.,7/1/2022
23793,Atli Geir Gunnarsson,Defensive Midfield,22.0,Unknown,NaN,NaN,UMF Njardvík,2. deild,Iceland,€25Th.,7/1/2022
23953,Borisav Zlataric,Right-Back,21.0,Unknown,NaN,NaN,Vranic,Serbia,Serbia,€10Th.,7/1/2022
24204,Víctor Barrientos,Left-Back,26.0,Unknown,NaN,NaN,Pastoreo Fútbol Club,Paraguay,Paraguay,€125Th.,7/1/2022
24308,Joshua Vargas,Left Midfield,27.0,Unknown,NaN,NaN,CD Honduras Progreso,Liga Nacional Apertura,Honduras,€50Th.,7/1/2022
24865,Aldo Fajardo,Centre-Forward,24.0,Unknown,NaN,NaN,CD Honduras Progreso,Liga Nacional Apertura,Honduras,€100Th.,7/1/2022
25206,Vlad Mocioaca,Centre-Back,20.0,Unknown,NaN,NaN,ACS Flacara Horezu,Romania,Romania,€10Th.,7/1/2022
25207,Raul Popa,defence,21.0,Unknown,NaN,NaN,Unirea Tomnatic,Romania,Romania,€10Th.,7/1/2022
25318,Rodrigo Herrera,midfield,23.0,Unknown,NaN,NaN,Once Deportivo FC,Primera División Apertura,El Salvador,€50Th.,7/1/2022
25755,Giovani Nikolic,Central Midfield,20.0,Unknown,NaN,NaN,CSC Peciu Nou,Romania,Romania,€10Th.,7/1/2022
25998,Osbed Pérez,defence,22.0,Unknown,NaN,NaN,CD Honduras Progreso,Liga Nacional Apertura,Honduras,€50Th.,7/1/2022
26103,Rafael Pocioian,midfield,17.0,Unknown,NaN,NaN,CS Corvinul 1921 Hunedoara,Romania,Romania,€10Th.,7/1/2022
26114,Antonio Verinac,Centre-Forward,17.0,Unknown,NaN,NaN,1.FC Lokomotive Leipzig,Regionalliga Northeast,Germany,€25Th.,7/1/2022
26151,Felipe Ponce,Attacking Midfield,34.0,Unknown,NaN,NaN,Aurora FC,Guatemala,Guatemala,€25Th.,7/1/2022
26243,Ionut Tataru,Centre-Back,32.0,Unknown,NaN,NaN,ACSO Filiasi,Romania,Romania,€50Th.,7/1/2022
26511,Óscar Salas,Left Midfield,28.0,Unknown,NaN,NaN,Deportivo Barberena FC,Guatemala,Guatemala,€100Th.,7/1/2022
26794,Carlo Vázquez,Centre-Forward,26.0,Unknown,NaN,NaN,Managua FC,Nicaragua,Nicaragua,€200Th.,7/1/2022
26800,Gabriel Braga,Central Midfield,27.0,Unknown,NaN,NaN,Sport Club Popesti Leordeni,Romania,Romania,€25Th.,7/1/2022
26876,Manasa Waqavou,Goalkeeper,28.0,Unknown,NaN,NaN,Rewa FA,Premier League,Fiji,€25Th.,7/1/2022
27330,Rafael Fernández,Centre-Back,21.0,Unknown,NaN,NaN,Querétaro FC,Liga MX Apertura,Mexico,€200Th.,7/1/2022
27466,Diego Areco,attack,29.0,Unknown,NaN,NaN,Managua FC,Nicaragua,Nicaragua,€75Th.,7/1/2022
27471,Cosmin Ofrim,defence,20.0,Unknown,NaN,NaN,CSM Sighetu Marmației,Romania,Romania,€10Th.,7/1/2022
27506,Juan Arce,Defensive Midfield,25.0,Unknown,NaN,NaN,Managua FC,Nicaragua,Nicaragua,€100Th.,7/1/2022

when origin_club,new_club = Unknown ==> league_origin_club,country_origin_club,league_new_club,country_new_club = NaN<br>

then we are fill this value by Unknown

#### data cleaning

fill league_origin_club and country_origin_club by Unknown when origin_club = Unknown or Without Club

In [101]:
df.loc[df["origin_club"] == "Unknown",["league_origin_club","country_origin_club"]]="Unknown"
df.loc[df["origin_club"] == "Without Club",["league_origin_club","country_origin_club"]]="Unknown"

fill league_new_club and country_new_club by Unknown when new_club = Unknown or Without Club

In [102]:
df.loc[df["new_club"] == "Unknown",["league_new_club","country_new_club"]]="UnKnown"
df.loc[df["new_club"] == "Without Club",["league_new_club","country_new_club"]]="UnKnown"

In [103]:
df.isna().sum()

name                     5
position                10
age                    148
origin_club              5
league_origin_club      29
country_origin_club     24
new_club                10
league_new_club        403
country_new_club       399
cost                     4
date_of_transfer         0
dtype: int64

make copy from dataframe df in df_new

In [104]:
df_new=df

In [105]:
df_new.isna().sum()

name                     5
position                10
age                    148
origin_club              5
league_origin_club      29
country_origin_club     24
new_club                10
league_new_club        403
country_new_club       399
cost                     4
date_of_transfer         0
dtype: int64

explore rows which ages not found

In [106]:
df[df["age"].isna()]

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
1727,Mohammadmehdi Mohammadpour,Attacking Midfield,NaN,Sepidrood Rasht FC,League 2,Iran,Damash Gilan FC,League 2,Iran,€25Th.,8/27/2022
1743,Harry Irving,Goalkeeper,NaN,Pontypridd United,Cymru Premier,Wales,Trethomas Bluebirds,Wales,Wales,€10Th.,8/27/2022
2919,Ebrahim Moradi,Right-Back,NaN,Vanpars,Azadegan League,Iran,Omid Vahdat Khorasan,Azadegan League,Iran,€75Th.,8/22/2022
2956,Hadi Kianpour,Attacking Midfield,NaN,Payam Toos R. Khorasan,League 2,Iran,Omid Vahdat Khorasan,Azadegan League,Iran,€25Th.,8/22/2022
3079,Tawfik Idsghir,Centre-Forward,NaN,Hassania d'Agadir U21,Morocco,Morocco,Olympique Dcheira,Morocco,Morocco,€25Th.,8/21/2022
...,...,...,...,...,...,...,...,...,...,...,...
33464,Mahamadou Dramé,midfield,NaN,FC Sète 34 B,France,France,FC Sète 34,National 2 - Grp. C,France,€50Th.,7/1/2022
33466,Lucas Davies,defence,NaN,Haverfordwest County U19,Wales,Wales,Haverfordwest County,Cymru Premier,Wales,€10Th.,7/1/2022
33592,Boris Bissemou,attack,NaN,CS Chebba,Tunisia,Tunisia,Without Club,UnKnown,UnKnown,€25Th.,7/1/2022
33605,Hossein Norouzi,Goalkeeper,NaN,Fajr Sepasi Shiraz,Azadegan League,Iran,Without Club,UnKnown,UnKnown,€25Th.,7/1/2022
33607,Erfan Sharifi,Left-Back,NaN,Khosheh Talaei Saveh,Azadegan League,Iran,Without Club,UnKnown,UnKnown,€25Th.,7/1/2022

we should fill data by scraping from transfermarket site

In [28]:
import requests_html

In [29]:
# make url from name of player
# https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query=erling+halland
# extract age for each player
session=requests_html.HTMLSession()
ages=[]
for index,row in df[df["age"].isna()].iterrows():
    url=f'https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query={"+".join(row["name"].split(" "))}'
    r=session.get(url)
    age=r.html.find("#yw0 > table > tbody > tr > td:nth-child(4)")[0].text
    ages.append(list([row["name"],age]))

In [30]:
# show information about above cell
len(ages),len(ages[0]),ages[0]

(148, 2, ['Mohammadmehdi Mohammadpour', '-'])

In [31]:
# save age for each player by name of player
for item in ages:
    df_new.loc[df["name"] == item[0],["age"]]=item[1]

In [32]:
df_new.isna().sum()

name                     5
position                10
age                      0
origin_club              5
league_origin_club      29
country_origin_club     24
new_club                10
league_new_club        403
country_new_club       399
cost                     4
date_of_transfer         0
dtype: int64

remove rows of players which name in it is null

return rows which name is not null in df_v2 dataframe

In [35]:
df_v2=df_new[df_new["name"].notna()]

In [36]:
df_v2.isnull().sum()

name                     0
position                 5
age                      0
origin_club              5
league_origin_club      29
country_origin_club     24
new_club                10
league_new_club        403
country_new_club       399
cost                     4
date_of_transfer         0
dtype: int64

then we are treat with missing value in name,age

fill missing values in positions by scraping position for each pleayer from transfer market

In [37]:
# make url from name of player like which in age cell
# extract position for each player
positions=[]
for index,row in df_v2[df_v2["position"].isna()].iterrows():
    url=f'https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query={"+".join(row["name"].split(" "))}'
    r=session.get(url)
    position=r.html.find("#yw0 > table > tbody > tr > td:nth-child(2)")[0].text
    positions.append([row["name"],position])
    
positions

[['Eljo Iba', 'RB'],
 ['Ángel Robles', 'GK'],
 ['Gian-Luca Reck', 'GK'],
 ['Kian Harratt', 'CF'],
 ['Michael Pavlovic', 'LB']]

In [38]:
# save positions for each player by name of player
for item in positions:
    df_v2.loc[df_v2["name"] == item[0],["position"]]=item[1]

C:\Users\engah\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
C:\Users\engah\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [39]:
df_v2.isna().sum()

name                     0
position                 0
age                      0
origin_club              5
league_origin_club      29
country_origin_club     24
new_club                10
league_new_club        403
country_new_club       399
cost                     4
date_of_transfer         0
dtype: int64

we are fill position too

fill missing values in Transfer market by scraping this for each pleayer from transfer market site

In [40]:
# make url from name of player like which in age cell
# extract costs (market transfer) for each player
costs=[]
for index,row in df_v2[df_v2["cost"].isna()].iterrows():
    url=f'https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query={"+".join(row["name"].split(" "))}'
    r=session.get(url)
    cost=r.html.find("#yw0 > table > tbody > tr > td.rechts.hauptlink")[0].text
    costs.append([row["name"],cost])
# save cost for each player by name of player
for item in costs:
    df_v2.loc[df_v2["name"] == item[0],["cost"]]=item[1]

In [41]:
df_v2.isnull().sum()

name                     0
position                 0
age                      0
origin_club              5
league_origin_club      29
country_origin_club     24
new_club                10
league_new_club        403
country_new_club       399
cost                     0
date_of_transfer         0
dtype: int64

fill missing values in origin_club by scraping origin_club for each pleayer from transfer market site

In [43]:
# make url from name of player like which in age cell and add anoter url for profile each player
# like this https://www.transfermarkt.com/marwan-hamdi/profil/spieler/557938
# extract old_clubs for each player
import re
olds_clubs=[]
for index,row in df_v2[df_v2["origin_club"].isna()].iterrows():
    url=f'https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query={"+".join(row["name"].split(" "))}'
    r=session.get(url)
    link=r.html.find("#yw0 > table > tbody > tr > td:nth-child(1) > table")[0].absolute_links
    link_1=0
    for index,j in enumerate(list(link)):
        if re.search("spieler",j) != None:
            link_1=j
    r_profile=session.get(link_1)
    old_club=r_profile.html.find("a.tm-player-transfer-history-grid__club-link")
    olds_clubs.append([row["name"],old_club[0].text])

In [44]:
olds_clubs

[['Eljo Iba', 'Persiba'],
 ['Ángel Robles', 'Miami'],
 ['Gian-Luca Reck', 'SV Lippstadt 08'],
 ['Kian Harratt', 'Bradford'],
 ['Michael Pavlovic', 'NK Olimpija']]

In [45]:
# save origin_club for each player by name of player
for item in olds_clubs:
    df_v2.loc[df_v2["name"] == item[0],["origin_club"]]=item[1]

In [46]:
df_v2.isnull().sum()

name                     0
position                 0
age                      0
origin_club              0
league_origin_club      29
country_origin_club     24
new_club                10
league_new_club        403
country_new_club       399
cost                     0
date_of_transfer         0
dtype: int64

In [48]:
df_v2.head()

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
0,Amine Gouiri,Centre-Forward,22.0,OGC Nice,Ligue 1,France,Stade Rennais FC,Ligue 1,France,€42.00m,9/1/2022
1,Umar Sadiq,Centre-Forward,25.0,UD Almería,LaLiga,Spain,Real Sociedad,LaLiga,Spain,€18.00m,9/1/2022
2,Carlos Soler,Central Midfield,25.0,Valencia CF,LaLiga,Spain,Paris Saint-Germain,Ligue 1,France,€50.00m,9/1/2022
3,Manuel Akanji,Centre-Back,27.0,Borussia Dortmund,Bundesliga,Germany,Manchester City,Premier League,England,€30.00m,9/1/2022
4,Wout Faes,Centre-Back,24.0,Stade Reims,Ligue 1,France,Leicester City,Premier League,England,€10.00m,9/1/2022

In [49]:
df_v2.isnull().sum()

name                     0
position                 0
age                      0
origin_club              0
league_origin_club      29
country_origin_club     24
new_club                10
league_new_club        403
country_new_club       399
cost                     0
date_of_transfer         0
dtype: int64

fill missing values in new_club by scraping origin_club for each pleayer from transfer market site

In [50]:
# make url from name of player like which in age cell 
# extract old_clubs for each player
new_clubs=[]
for index,row in df_v2[df_v2["new_club"].isna()].iterrows():
    url=f'https://www.transfermarkt.com/schnellsuche/ergebnis/schnellsuche?query={"+".join(row["name"].split(" "))}'
    r=session.get(url)
    club=r.html.find('#yw0 > table > tbody > tr > td:nth-child(1) > table')
    new_clubs.append([row["name"],club[0].text.split("\n")[1]])

In [51]:
new_clubs

[['Matteo Gullo', 'Vigor Lamezia Calcio'],
 ['Hamed Alizadeh', 'Darya Caspian'],
 ['Thanachach Phocha', 'Banbueng FC'],
 ['Richard Keogh', 'Ipswich Town'],
 ['Uros Poljanec', 'NK Pesnica'],
 ['Bastien Héry', 'Galway United FC'],
 ['Farid Mohammadian', 'Without Club'],
 ['Sajjad Abbasi', 'Without Club'],
 ['Abdallahi Mahmoud', 'Deportivo Alavés'],
 ['Gleb Shilov', 'Without Club']]

In [52]:
# save new_club for each player by name of player
for item in new_clubs:
    df_v2.loc[df_v2["name"] == item[0],["new_club"]]=item[1]

C:\Users\engah\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
C:\Users\engah\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [53]:
df_v2.isnull().sum()

name                     0
position                 0
age                      0
origin_club              0
league_origin_club      29
country_origin_club     24
new_club                 0
league_new_club        403
country_new_club       399
cost                     0
date_of_transfer         0
dtype: int64

we hopw we fill missing value by correct way.

league_origin_club,country_origin_club,league_new_club,country_new_club , this columns until contain missing value , we can apply function fillna to fill it by static value = UnKnown

In [54]:
cols=['league_origin_club','country_origin_club','league_new_club','country_new_club']
for col in cols:
    df_v2[col].fillna("Unknown",inplace=True)

C:\Users\engah\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

check values

In [55]:
df_v2.isna().sum()

name                   0
position               0
age                    0
origin_club            0
league_origin_club     0
country_origin_club    0
new_club               0
league_new_club        0
country_new_club       0
cost                   0
date_of_transfer       0
dtype: int64

In [56]:
df_v2.shape

(33620, 11)

In [58]:
df_v2.position.value_counts()

Centre-Back           5338
Centre-Forward        4997
Central Midfield      3627
Goalkeeper            3359
Defensive Midfield    2488
Right-Back            2414
Left-Back             2360
Attacking Midfield    2303
Left Winger           2260
Right Winger          2170
midfield               532
Right Midfield         463
Left Midfield          414
attack                 316
Second Striker         314
defence                260
GK                       2
RB                       1
CF                       1
LB                       1
Name: position, dtype: int64

we should replace ==> {GK:Goalkeeper,RB:Right-Back,CF:Centre-Forward,LB:Left-Back}

In [62]:
# this will replace "[GK,RB,CF,LB]" with "[Goalkeeper,Right-Back,Centre-Forward,Left-Back,]"
df_v2.replace(to_replace="GK",value="Goalkeeper",inplace=True)
df_v2.replace(to_replace="RB",value="Right-Back",inplace=True)
df_v2.replace(to_replace="CF",value="Centre-Forward",inplace=True)
df_v2.replace(to_replace="LB",value="Left-Back",inplace=True)

In [63]:
df_v2.position.value_counts()

Centre-Back           5338
Centre-Forward        4998
Central Midfield      3627
Goalkeeper            3361
Defensive Midfield    2488
Right-Back            2415
Left-Back             2361
Attacking Midfield    2303
Left Winger           2260
Right Winger          2170
midfield               532
Right Midfield         463
Left Midfield          414
attack                 316
Second Striker         314
defence                260
Name: position, dtype: int64

when we extract ages from transfer market we chance, players not have ages in this site and it can cause some problem , so we try to treat with it

In [64]:
df[df["age"] == '-']

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
1727,Mohammadmehdi Mohammadpour,Attacking Midfield,-,Sepidrood Rasht FC,League 2,Iran,Damash Gilan FC,League 2,Iran,€25Th.,8/27/2022
1743,Harry Irving,Goalkeeper,-,Pontypridd United,Cymru Premier,Wales,Trethomas Bluebirds,Wales,Wales,€10Th.,8/27/2022
2919,Ebrahim Moradi,Right-Back,-,Vanpars,Azadegan League,Iran,Omid Vahdat Khorasan,Azadegan League,Iran,€75Th.,8/22/2022
2956,Hadi Kianpour,Attacking Midfield,-,Payam Toos R. Khorasan,League 2,Iran,Omid Vahdat Khorasan,Azadegan League,Iran,€25Th.,8/22/2022
3079,Tawfik Idsghir,Centre-Forward,-,Hassania d'Agadir U21,Morocco,Morocco,Olympique Dcheira,Morocco,Morocco,€25Th.,8/21/2022
...,...,...,...,...,...,...,...,...,...,...,...
33460,Reza Jalali,Goalkeeper,-,Foolad FC,Persian Gulf Pro League,Iran,Without Club,UnKnown,UnKnown,€25Th.,7/1/2022
33466,Lucas Davies,defence,-,Haverfordwest County U19,Wales,Wales,Haverfordwest County,Cymru Premier,Wales,€10Th.,7/1/2022
33592,Boris Bissemou,attack,-,CS Chebba,Tunisia,Tunisia,Without Club,UnKnown,UnKnown,€25Th.,7/1/2022
33605,Hossein Norouzi,Goalkeeper,-,Fajr Sepasi Shiraz,Azadegan League,Iran,Without Club,UnKnown,UnKnown,€25Th.,7/1/2022
33607,Erfan Sharifi,Left-Back,-,Khosheh Talaei Saveh,Azadegan League,Iran,Without Club,UnKnown,UnKnown,€25Th.,7/1/2022

we drop this ages from data to convert age to float datatypes

In [65]:
df_v2.drop(df[df['age'] == "-"].index,inplace=True)
df_v2.shape

C:\Users\engah\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

(33495, 11)

check duplicates value

In [67]:
df_v2.duplicated().sum()

0

there are no duplicated values

In [71]:
df_v2.describe(include=object)

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
count,33495,33495,33495.0,33495,33495,33495,33495,33495,33495,33495,33495
unique,32454,16,46.0,5811,463,154,6306,465,141,118,63
top,Rafinha,Centre-Back,21.0,Without Club,Unknown,Italy,Without Club,UnKnown,UnKnown,€50Th.,7/1/2022
freq,7,5328,2984.0,851,937,4759,4917,5137,5137,5098,14309

we show age is object column and we should convert it to float columns

In [82]:
df_v2["age"]= df_v2["age"].astype(float)

C:\Users\engah\AppData\Local\Temp/ipykernel_14900/3959015322.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_v2["age"]= df_v2["age"].astype(float)

In [83]:
df_v2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33495 entries, 0 to 33624
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 33495 non-null  object
 1   position             33495 non-null  object
 2   age                  33495 non-null  float64
 3   origin_club          33495 non-null  object
 4   league_origin_club   33495 non-null  object
 5   country_origin_club  33495 non-null  object
 6   new_club             33495 non-null  object
 7   league_new_club      33495 non-null  object
 8   country_new_club     33495 non-null  object
 9   cost                 33495 non-null  object
 10  date_of_transfer     33495 non-null  object
dtypes: float64(1), object(10)
memory usage: 3.1+ MB

In [85]:
df_v2.describe()

                age
count  33495.000000
mean      25.023914
std        4.791384
min       15.000000
25%       21.000000
50%       24.000000
75%       28.000000
max       54.000000

In [86]:
df_v2[df_v2["age"] == 54]

,name,position,age,origin_club,league_origin_club,country_origin_club,new_club,league_new_club,country_new_club,cost,date_of_transfer
25945,Anderson Gómez,Right-Back,54.0,CD Atlético Marte,Primera División Apertura,El Salvador,Ilopango FC,El Salvador,El Salvador,€10Th.,7/1/2022
26074,Fernando Ruíz,midfield,54.0,Veraguas United FC,Liga Panameña Clausura,Panama,Unknown,UnKnown,UnKnown,€25Th.,7/1/2022

we found rows which ages equal 54 and it is consider outlier,we must drop it

In [88]:
df_v2.drop(df_v2[df_v2['age'] == 54].index,inplace=True)

C:\Users\engah\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [89]:
df_v2.shape

(33493, 11)

final i think, we finish step cleaning for data and we export csv file from dataframe

In [90]:
df_v2.to_csv("cleaned_data.csv")